name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User App Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: sasidhar6/no-hunger:latest
          
      - name: Build and Push Bank Webhook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: sasidhar6/bank-webhook:latest

      - name: Verify Pushed Images
        run: |
          docker pull sasidhar6/no-hunger:latest
          docker pull sasidhar6/bank-webhook:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull and deploy user app
            sudo docker pull sasidhar6/no-hunger:latest
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -d --name web-app -p 3005:3000 sasidhar6/no-hunger:latest
            
            # Pull and deploy bank webhook
            sudo docker pull sasidhar6/bank-webhook:latest
            sudo docker stop webhook-app || true
            sudo docker rm webhook-app || true
            sudo docker run -d --name webhook-app -p 3003:3003 sasidhar6/bank-webhook:latest
