name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User App Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: sasidhar6/no-hunger:latest
          build-args: |
            NEXT_PUBLIC_WEBHOOK_URL=${{ secrets.NEXT_PUBLIC_WEBHOOK_URL }}

      - name: Build and Push Bank Webhook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: sasidhar6/bank-webhook:latest

      - name: Verify Pushed Images
        run: |
          docker pull sasidhar6/no-hunger:latest
          docker pull sasidhar6/bank-webhook:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Delete old images
            docker rmi sasidhar6/no-hunger:latest || true
            docker rmi sasidhar6/bank-webhook:latest || true

            # Pull and deploy user app
            docker pull sasidhar6/no-hunger:latest
            docker stop web-app || true
            docker rm web-app || true
            docker run -d --name web-app \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
              -e NEXT_PUBLIC_WEBHOOK_URL="${{ secrets.NEXT_PUBLIC_WEBHOOK_URL }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -p 3005:3000 sasidhar6/no-hunger:latest

            # Pull and deploy bank webhook
            docker pull sasidhar6/bank-webhook:latest
            docker stop webhook-app || true
            docker rm webhook-app || true
            docker run -d --name webhook-app \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -p 3003:3003 sasidhar6/bank-webhook:latest
